### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by CloudViking86** [austoonz/Convert#3]
Hello,

```
Invalid endpoint: https://s3..amazonaws.com
  - Failed to download InvokeBuild
Failed to download InvokeBuild
At C:\Users\user\git\Convert\install_modules.ps1:104 char:9
+         throw $message
+         ~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Failed to download InvokeBuild:String) [], RuntimeException
    + FullyQualifiedErrorId : Failed to download InvokeBuild
```

Is your S3-bucket and/or this bucket still alive? :)

Oh and also the links here;
https://convert.readthedocs.io/en/latest/
gives 404:s.

Best Regards - CloudViking86

**Comment by austoonz** [comment]
Thank your for the notes.

1. The S3 Bucket referenced in the ```install_modules.ps1``` file is purely used for my build process. The module can be installed from the PowerShell Gallery.

2. The documentation pages on readthedocs.io work for me - I've just tried from a few different computers and internet connections. (!?)

**Comment by CloudViking86** [comment]
Thank you for your reply, appreciate it.

Regarding the 404s;
https://convert.readthedocs.io/en/latest/

Both links under:
Release notes
and
Changelog
gives me 404s for some reason :/

Thank you for the installation instructions, just thought I should run the .ps1-file but then I know :)
________________________________

**Comment by austoonz** [comment]
Thanks for the note on those... I'll look at getting those updates on RTD. I'll leave this issue open until I've sorted that.

**Comment by austoonz** [comment]
Updated the index page. Closing.
